name = "glove"
version = "1.0.0"
description = "Gleam QBE IR Generator"
licences = ["MIT"]
repository = { type = "github", user = "Willyboar", repo = "glove" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
