name = "glove"
version = "0.4.0"
description = "Gleam QBE IR Generator"
licences = ["MIT"]
repository = { type = "github", user = "Willyboar", repo = "glove" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"